namespace Models.AdvApi
{
	public enum SearchIndex
	{
		All = 1,
		Apparel = 2,
		Appliances = 3,
		ArtsAndCrafts = 4,
		Automotive = 5,
		Baby = 6,
		Beauty = 7,
		Blended = 8,
		Books = 9,
		Classical = 10,
		Collectibles = 11,
		DigitalMusic = 12,
		Grocery = 13,
		DVD = 14,
		Electronics = 15,
		HealthPersonalCare = 16,
		HomeGarden = 17,
		Industrial = 18,
		Jewelry = 19,
		KindleStore = 20,
		Kitchen = 21,
		LawnAndGarden = 22,
		Magazines = 23,
		Marketplace = 24,
		Merchants = 25,
		Miscellaneous = 26,
		MobileApps = 27,
		MP3Downloads = 28,
		Music = 29,
		MusicalInstruments = 30,
		MusicTracks = 31,
		OfficeProducts = 32,
		OutdoorLiving = 33,
		PCHardware = 34,
		PetSupplies = 35,
		Photo = 36,
		Shoes = 37,
		Software = 38,
		SportingGoods = 39,
		Tools = 40,
		Toys = 41,
		UnboxVideo = 42,
		VHS = 43,
		Video = 44,
		VideoGames = 45,
		Watches = 46,
		Wireless = 47,
		WirelessAccessories = 48
	}
}
