#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="amazonmws")]
	internal partial class AmazonMWSdbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertManufacturer(Manufacturer instance);
    partial void UpdateManufacturer(Manufacturer instance);
    partial void DeleteManufacturer(Manufacturer instance);
    partial void InsertAllOrdersData(AllOrdersData instance);
    partial void UpdateAllOrdersData(AllOrdersData instance);
    partial void DeleteAllOrdersData(AllOrdersData instance);
    partial void InsertUnsuppressedInventoryData(UnsuppressedInventoryData instance);
    partial void UpdateUnsuppressedInventoryData(UnsuppressedInventoryData instance);
    partial void DeleteUnsuppressedInventoryData(UnsuppressedInventoryData instance);
    partial void InsertFeePreviewData(FeePreviewData instance);
    partial void UpdateFeePreviewData(FeePreviewData instance);
    partial void DeleteFeePreviewData(FeePreviewData instance);
    partial void InsertPriceHistory(PriceHistory instance);
    partial void UpdatePriceHistory(PriceHistory instance);
    partial void DeletePriceHistory(PriceHistory instance);
    partial void InsertListingOffersLog(ListingOffersLog instance);
    partial void UpdateListingOffersLog(ListingOffersLog instance);
    partial void DeleteListingOffersLog(ListingOffersLog instance);
    partial void InsertProduct(Product instance);
    partial void UpdateProduct(Product instance);
    partial void DeleteProduct(Product instance);
    #endregion
		
		public AmazonMWSdbDataContext() : 
				base(global::Data.Properties.Settings.Default.amazonmwsConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AmazonMWSdbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AmazonMWSdbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AmazonMWSdbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AmazonMWSdbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Manufacturer> Manufacturers
		{
			get
			{
				return this.GetTable<Manufacturer>();
			}
		}
		
		public System.Data.Linq.Table<AllOrdersData> AllOrdersDatas
		{
			get
			{
				return this.GetTable<AllOrdersData>();
			}
		}
		
		public System.Data.Linq.Table<UnsuppressedInventoryData> UnsuppressedInventoryDatas
		{
			get
			{
				return this.GetTable<UnsuppressedInventoryData>();
			}
		}
		
		public System.Data.Linq.Table<FeePreviewData> FeePreviewDatas
		{
			get
			{
				return this.GetTable<FeePreviewData>();
			}
		}
		
		public System.Data.Linq.Table<PriceHistory> PriceHistories
		{
			get
			{
				return this.GetTable<PriceHistory>();
			}
		}
		
		public System.Data.Linq.Table<ListingOffersLog> ListingOffersLogs
		{
			get
			{
				return this.GetTable<ListingOffersLog>();
			}
		}
		
		public System.Data.Linq.Table<Product> Products
		{
			get
			{
				return this.GetTable<Product>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Manufacturers")]
	public partial class Manufacturer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ManufacturerId;
		
		private string _Name;
		
		private EntitySet<Product> _Products;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnManufacturerIdChanging(int value);
    partial void OnManufacturerIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public Manufacturer()
		{
			this._Products = new EntitySet<Product>(new Action<Product>(this.attach_Products), new Action<Product>(this.detach_Products));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ManufacturerId", AutoSync=AutoSync.OnInsert, DbType="INT NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ManufacturerId
		{
			get
			{
				return this._ManufacturerId;
			}
			set
			{
				if ((this._ManufacturerId != value))
				{
					this.OnManufacturerIdChanging(value);
					this.SendPropertyChanging();
					this._ManufacturerId = value;
					this.SendPropertyChanged("ManufacturerId");
					this.OnManufacturerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Manufacturer_Product", Storage="_Products", ThisKey="ManufacturerId", OtherKey="ManufacturerId")]
		public EntitySet<Product> Products
		{
			get
			{
				return this._Products;
			}
			set
			{
				this._Products.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Products(Product entity)
		{
			this.SendPropertyChanging();
			entity.Manufacturer = this;
		}
		
		private void detach_Products(Product entity)
		{
			this.SendPropertyChanging();
			entity.Manufacturer = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AllOrdersData")]
	public partial class AllOrdersData : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _amazon_order_id;
		
		private string _sku;
		
		private string _asin;
		
		private string _product_name;
		
		private string _merchant_order_id;
		
		private System.Nullable<System.DateTime> _purchase_date;
		
		private System.Nullable<System.DateTime> _last_updated_date;
		
		private string _order_status;
		
		private string _fulfillment_channel;
		
		private string _sales_channel;
		
		private string _order_channel;
		
		private string _url;
		
		private string _ship_service_level;
		
		private string _item_status;
		
		private System.Nullable<long> _quantity;
		
		private string _currency;
		
		private System.Nullable<decimal> _item_price;
		
		private System.Nullable<decimal> _item_tax;
		
		private System.Nullable<decimal> _shipping_price;
		
		private System.Nullable<decimal> _shipping_tax;
		
		private System.Nullable<decimal> _gift_wrap_price;
		
		private System.Nullable<decimal> _gift_wrap_tax;
		
		private System.Nullable<decimal> _item_promotion_discount;
		
		private System.Nullable<decimal> _ship_promotion_discount;
		
		private string _ship_city;
		
		private string _ship_state;
		
		private string _ship_postal_code;
		
		private string _ship_country;
		
		private string _promotion_ids;
		
		private EntityRef<Product> _Product;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onamazon_order_idChanging(string value);
    partial void Onamazon_order_idChanged();
    partial void OnskuChanging(string value);
    partial void OnskuChanged();
    partial void OnasinChanging(string value);
    partial void OnasinChanged();
    partial void Onproduct_nameChanging(string value);
    partial void Onproduct_nameChanged();
    partial void Onmerchant_order_idChanging(string value);
    partial void Onmerchant_order_idChanged();
    partial void Onpurchase_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onpurchase_dateChanged();
    partial void Onlast_updated_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onlast_updated_dateChanged();
    partial void Onorder_statusChanging(string value);
    partial void Onorder_statusChanged();
    partial void Onfulfillment_channelChanging(string value);
    partial void Onfulfillment_channelChanged();
    partial void Onsales_channelChanging(string value);
    partial void Onsales_channelChanged();
    partial void Onorder_channelChanging(string value);
    partial void Onorder_channelChanged();
    partial void OnurlChanging(string value);
    partial void OnurlChanged();
    partial void Onship_service_levelChanging(string value);
    partial void Onship_service_levelChanged();
    partial void Onitem_statusChanging(string value);
    partial void Onitem_statusChanged();
    partial void OnquantityChanging(System.Nullable<long> value);
    partial void OnquantityChanged();
    partial void OncurrencyChanging(string value);
    partial void OncurrencyChanged();
    partial void Onitem_priceChanging(System.Nullable<decimal> value);
    partial void Onitem_priceChanged();
    partial void Onitem_taxChanging(System.Nullable<decimal> value);
    partial void Onitem_taxChanged();
    partial void Onshipping_priceChanging(System.Nullable<decimal> value);
    partial void Onshipping_priceChanged();
    partial void Onshipping_taxChanging(System.Nullable<decimal> value);
    partial void Onshipping_taxChanged();
    partial void Ongift_wrap_priceChanging(System.Nullable<decimal> value);
    partial void Ongift_wrap_priceChanged();
    partial void Ongift_wrap_taxChanging(System.Nullable<decimal> value);
    partial void Ongift_wrap_taxChanged();
    partial void Onitem_promotion_discountChanging(System.Nullable<decimal> value);
    partial void Onitem_promotion_discountChanged();
    partial void Onship_promotion_discountChanging(System.Nullable<decimal> value);
    partial void Onship_promotion_discountChanged();
    partial void Onship_cityChanging(string value);
    partial void Onship_cityChanged();
    partial void Onship_stateChanging(string value);
    partial void Onship_stateChanged();
    partial void Onship_postal_codeChanging(string value);
    partial void Onship_postal_codeChanged();
    partial void Onship_countryChanging(string value);
    partial void Onship_countryChanged();
    partial void Onpromotion_idsChanging(string value);
    partial void Onpromotion_idsChanged();
    #endregion
		
		public AllOrdersData()
		{
			this._Product = default(EntityRef<Product>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[amazon-order-id]", Storage="_amazon_order_id", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string amazon_order_id
		{
			get
			{
				return this._amazon_order_id;
			}
			set
			{
				if ((this._amazon_order_id != value))
				{
					this.Onamazon_order_idChanging(value);
					this.SendPropertyChanging();
					this._amazon_order_id = value;
					this.SendPropertyChanged("amazon_order_id");
					this.Onamazon_order_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sku", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string sku
		{
			get
			{
				return this._sku;
			}
			set
			{
				if ((this._sku != value))
				{
					this.OnskuChanging(value);
					this.SendPropertyChanging();
					this._sku = value;
					this.SendPropertyChanged("sku");
					this.OnskuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_asin", DbType="NVarChar(20)")]
		public string asin
		{
			get
			{
				return this._asin;
			}
			set
			{
				if ((this._asin != value))
				{
					if (this._Product.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnasinChanging(value);
					this.SendPropertyChanging();
					this._asin = value;
					this.SendPropertyChanged("asin");
					this.OnasinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[product-name]", Storage="_product_name", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string product_name
		{
			get
			{
				return this._product_name;
			}
			set
			{
				if ((this._product_name != value))
				{
					this.Onproduct_nameChanging(value);
					this.SendPropertyChanging();
					this._product_name = value;
					this.SendPropertyChanged("product_name");
					this.Onproduct_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[merchant-order-id]", Storage="_merchant_order_id", DbType="NVarChar(20)")]
		public string merchant_order_id
		{
			get
			{
				return this._merchant_order_id;
			}
			set
			{
				if ((this._merchant_order_id != value))
				{
					this.Onmerchant_order_idChanging(value);
					this.SendPropertyChanging();
					this._merchant_order_id = value;
					this.SendPropertyChanged("merchant_order_id");
					this.Onmerchant_order_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[purchase-date]", Storage="_purchase_date", DbType="DateTime2")]
		public System.Nullable<System.DateTime> purchase_date
		{
			get
			{
				return this._purchase_date;
			}
			set
			{
				if ((this._purchase_date != value))
				{
					this.Onpurchase_dateChanging(value);
					this.SendPropertyChanging();
					this._purchase_date = value;
					this.SendPropertyChanged("purchase_date");
					this.Onpurchase_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[last-updated-date]", Storage="_last_updated_date", DbType="DateTime2")]
		public System.Nullable<System.DateTime> last_updated_date
		{
			get
			{
				return this._last_updated_date;
			}
			set
			{
				if ((this._last_updated_date != value))
				{
					this.Onlast_updated_dateChanging(value);
					this.SendPropertyChanging();
					this._last_updated_date = value;
					this.SendPropertyChanged("last_updated_date");
					this.Onlast_updated_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[order-status]", Storage="_order_status", DbType="NVarChar(10)")]
		public string order_status
		{
			get
			{
				return this._order_status;
			}
			set
			{
				if ((this._order_status != value))
				{
					this.Onorder_statusChanging(value);
					this.SendPropertyChanging();
					this._order_status = value;
					this.SendPropertyChanged("order_status");
					this.Onorder_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[fulfillment-channel]", Storage="_fulfillment_channel", DbType="NVarChar(20)")]
		public string fulfillment_channel
		{
			get
			{
				return this._fulfillment_channel;
			}
			set
			{
				if ((this._fulfillment_channel != value))
				{
					this.Onfulfillment_channelChanging(value);
					this.SendPropertyChanging();
					this._fulfillment_channel = value;
					this.SendPropertyChanged("fulfillment_channel");
					this.Onfulfillment_channelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[sales-channel]", Storage="_sales_channel", DbType="NVarChar(20)")]
		public string sales_channel
		{
			get
			{
				return this._sales_channel;
			}
			set
			{
				if ((this._sales_channel != value))
				{
					this.Onsales_channelChanging(value);
					this.SendPropertyChanging();
					this._sales_channel = value;
					this.SendPropertyChanged("sales_channel");
					this.Onsales_channelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[order-channel]", Storage="_order_channel", DbType="NVarChar(20)")]
		public string order_channel
		{
			get
			{
				return this._order_channel;
			}
			set
			{
				if ((this._order_channel != value))
				{
					this.Onorder_channelChanging(value);
					this.SendPropertyChanging();
					this._order_channel = value;
					this.SendPropertyChanged("order_channel");
					this.Onorder_channelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_url", DbType="NVarChar(50)")]
		public string url
		{
			get
			{
				return this._url;
			}
			set
			{
				if ((this._url != value))
				{
					this.OnurlChanging(value);
					this.SendPropertyChanging();
					this._url = value;
					this.SendPropertyChanged("url");
					this.OnurlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ship-service-level]", Storage="_ship_service_level", DbType="NVarChar(20)")]
		public string ship_service_level
		{
			get
			{
				return this._ship_service_level;
			}
			set
			{
				if ((this._ship_service_level != value))
				{
					this.Onship_service_levelChanging(value);
					this.SendPropertyChanging();
					this._ship_service_level = value;
					this.SendPropertyChanged("ship_service_level");
					this.Onship_service_levelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[item-status]", Storage="_item_status", DbType="NVarChar(20)")]
		public string item_status
		{
			get
			{
				return this._item_status;
			}
			set
			{
				if ((this._item_status != value))
				{
					this.Onitem_statusChanging(value);
					this.SendPropertyChanging();
					this._item_status = value;
					this.SendPropertyChanged("item_status");
					this.Onitem_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity", DbType="BigInt")]
		public System.Nullable<long> quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				if ((this._quantity != value))
				{
					this.OnquantityChanging(value);
					this.SendPropertyChanging();
					this._quantity = value;
					this.SendPropertyChanged("quantity");
					this.OnquantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_currency", DbType="NVarChar(20)")]
		public string currency
		{
			get
			{
				return this._currency;
			}
			set
			{
				if ((this._currency != value))
				{
					this.OncurrencyChanging(value);
					this.SendPropertyChanging();
					this._currency = value;
					this.SendPropertyChanged("currency");
					this.OncurrencyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[item-price]", Storage="_item_price", DbType="Money")]
		public System.Nullable<decimal> item_price
		{
			get
			{
				return this._item_price;
			}
			set
			{
				if ((this._item_price != value))
				{
					this.Onitem_priceChanging(value);
					this.SendPropertyChanging();
					this._item_price = value;
					this.SendPropertyChanged("item_price");
					this.Onitem_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[item-tax]", Storage="_item_tax", DbType="Money")]
		public System.Nullable<decimal> item_tax
		{
			get
			{
				return this._item_tax;
			}
			set
			{
				if ((this._item_tax != value))
				{
					this.Onitem_taxChanging(value);
					this.SendPropertyChanging();
					this._item_tax = value;
					this.SendPropertyChanged("item_tax");
					this.Onitem_taxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[shipping-price]", Storage="_shipping_price", DbType="Money")]
		public System.Nullable<decimal> shipping_price
		{
			get
			{
				return this._shipping_price;
			}
			set
			{
				if ((this._shipping_price != value))
				{
					this.Onshipping_priceChanging(value);
					this.SendPropertyChanging();
					this._shipping_price = value;
					this.SendPropertyChanged("shipping_price");
					this.Onshipping_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[shipping-tax]", Storage="_shipping_tax", DbType="Money")]
		public System.Nullable<decimal> shipping_tax
		{
			get
			{
				return this._shipping_tax;
			}
			set
			{
				if ((this._shipping_tax != value))
				{
					this.Onshipping_taxChanging(value);
					this.SendPropertyChanging();
					this._shipping_tax = value;
					this.SendPropertyChanged("shipping_tax");
					this.Onshipping_taxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[gift-wrap-price]", Storage="_gift_wrap_price", DbType="Money")]
		public System.Nullable<decimal> gift_wrap_price
		{
			get
			{
				return this._gift_wrap_price;
			}
			set
			{
				if ((this._gift_wrap_price != value))
				{
					this.Ongift_wrap_priceChanging(value);
					this.SendPropertyChanging();
					this._gift_wrap_price = value;
					this.SendPropertyChanged("gift_wrap_price");
					this.Ongift_wrap_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[gift-wrap-tax]", Storage="_gift_wrap_tax", DbType="Money")]
		public System.Nullable<decimal> gift_wrap_tax
		{
			get
			{
				return this._gift_wrap_tax;
			}
			set
			{
				if ((this._gift_wrap_tax != value))
				{
					this.Ongift_wrap_taxChanging(value);
					this.SendPropertyChanging();
					this._gift_wrap_tax = value;
					this.SendPropertyChanged("gift_wrap_tax");
					this.Ongift_wrap_taxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[item-promotion-discount]", Storage="_item_promotion_discount", DbType="Money")]
		public System.Nullable<decimal> item_promotion_discount
		{
			get
			{
				return this._item_promotion_discount;
			}
			set
			{
				if ((this._item_promotion_discount != value))
				{
					this.Onitem_promotion_discountChanging(value);
					this.SendPropertyChanging();
					this._item_promotion_discount = value;
					this.SendPropertyChanged("item_promotion_discount");
					this.Onitem_promotion_discountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ship-promotion-discount]", Storage="_ship_promotion_discount", DbType="Money")]
		public System.Nullable<decimal> ship_promotion_discount
		{
			get
			{
				return this._ship_promotion_discount;
			}
			set
			{
				if ((this._ship_promotion_discount != value))
				{
					this.Onship_promotion_discountChanging(value);
					this.SendPropertyChanging();
					this._ship_promotion_discount = value;
					this.SendPropertyChanged("ship_promotion_discount");
					this.Onship_promotion_discountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ship-city]", Storage="_ship_city", DbType="NVarChar(50)")]
		public string ship_city
		{
			get
			{
				return this._ship_city;
			}
			set
			{
				if ((this._ship_city != value))
				{
					this.Onship_cityChanging(value);
					this.SendPropertyChanging();
					this._ship_city = value;
					this.SendPropertyChanged("ship_city");
					this.Onship_cityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ship-state]", Storage="_ship_state", DbType="NVarChar(20)")]
		public string ship_state
		{
			get
			{
				return this._ship_state;
			}
			set
			{
				if ((this._ship_state != value))
				{
					this.Onship_stateChanging(value);
					this.SendPropertyChanging();
					this._ship_state = value;
					this.SendPropertyChanged("ship_state");
					this.Onship_stateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ship-postal-code]", Storage="_ship_postal_code", DbType="NVarChar(20)")]
		public string ship_postal_code
		{
			get
			{
				return this._ship_postal_code;
			}
			set
			{
				if ((this._ship_postal_code != value))
				{
					this.Onship_postal_codeChanging(value);
					this.SendPropertyChanging();
					this._ship_postal_code = value;
					this.SendPropertyChanged("ship_postal_code");
					this.Onship_postal_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ship-country]", Storage="_ship_country", DbType="NVarChar(50)")]
		public string ship_country
		{
			get
			{
				return this._ship_country;
			}
			set
			{
				if ((this._ship_country != value))
				{
					this.Onship_countryChanging(value);
					this.SendPropertyChanging();
					this._ship_country = value;
					this.SendPropertyChanged("ship_country");
					this.Onship_countryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[promotion-ids]", Storage="_promotion_ids", DbType="NVarChar(50)")]
		public string promotion_ids
		{
			get
			{
				return this._promotion_ids;
			}
			set
			{
				if ((this._promotion_ids != value))
				{
					this.Onpromotion_idsChanging(value);
					this.SendPropertyChanging();
					this._promotion_ids = value;
					this.SendPropertyChanged("promotion_ids");
					this.Onpromotion_idsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Product_AllOrdersData", Storage="_Product", ThisKey="asin", OtherKey="ASIN", IsForeignKey=true)]
		public Product Product
		{
			get
			{
				return this._Product.Entity;
			}
			set
			{
				Product previousValue = this._Product.Entity;
				if (((previousValue != value) 
							|| (this._Product.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Product.Entity = null;
						previousValue.AllOrdersDatas.Remove(this);
					}
					this._Product.Entity = value;
					if ((value != null))
					{
						value.AllOrdersDatas.Add(this);
						this._asin = value.ASIN;
					}
					else
					{
						this._asin = default(string);
					}
					this.SendPropertyChanged("Product");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UnsuppressedInventoryData")]
	public partial class UnsuppressedInventoryData : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _UnsuppressedInventoryDataId;
		
		private System.Nullable<System.DateTime> _Date;
		
		private string _sku;
		
		private string _fnsku;
		
		private string _asin;
		
		private string _product_name;
		
		private string _condition;
		
		private System.Nullable<decimal> _your_price;
		
		private string _mfn_listing_exists;
		
		private System.Nullable<long> _mfn_fulfillable_quantity;
		
		private string _afn_listing_exists;
		
		private System.Nullable<long> _afn_warehouse_quantity;
		
		private System.Nullable<long> _afn_fulfillable_quantity;
		
		private System.Nullable<long> _afn_unsellable_quantity;
		
		private System.Nullable<long> _afn_reserved_quantity;
		
		private System.Nullable<long> _afn_total_quantity;
		
		private System.Nullable<decimal> _per_unit_volume;
		
		private System.Nullable<long> _afn_inbound_working_quantity;
		
		private System.Nullable<long> _afn_inbound_shipped_quantity;
		
		private System.Nullable<long> _afn_inbound_receiving_quantity;
		
		private EntityRef<Product> _Product;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUnsuppressedInventoryDataIdChanging(long value);
    partial void OnUnsuppressedInventoryDataIdChanged();
    partial void OnDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDateChanged();
    partial void OnskuChanging(string value);
    partial void OnskuChanged();
    partial void OnfnskuChanging(string value);
    partial void OnfnskuChanged();
    partial void OnasinChanging(string value);
    partial void OnasinChanged();
    partial void Onproduct_nameChanging(string value);
    partial void Onproduct_nameChanged();
    partial void OnconditionChanging(string value);
    partial void OnconditionChanged();
    partial void Onyour_priceChanging(System.Nullable<decimal> value);
    partial void Onyour_priceChanged();
    partial void Onmfn_listing_existsChanging(string value);
    partial void Onmfn_listing_existsChanged();
    partial void Onmfn_fulfillable_quantityChanging(System.Nullable<long> value);
    partial void Onmfn_fulfillable_quantityChanged();
    partial void Onafn_listing_existsChanging(string value);
    partial void Onafn_listing_existsChanged();
    partial void Onafn_warehouse_quantityChanging(System.Nullable<long> value);
    partial void Onafn_warehouse_quantityChanged();
    partial void Onafn_fulfillable_quantityChanging(System.Nullable<long> value);
    partial void Onafn_fulfillable_quantityChanged();
    partial void Onafn_unsellable_quantityChanging(System.Nullable<long> value);
    partial void Onafn_unsellable_quantityChanged();
    partial void Onafn_reserved_quantityChanging(System.Nullable<long> value);
    partial void Onafn_reserved_quantityChanged();
    partial void Onafn_total_quantityChanging(System.Nullable<long> value);
    partial void Onafn_total_quantityChanged();
    partial void Onper_unit_volumeChanging(System.Nullable<decimal> value);
    partial void Onper_unit_volumeChanged();
    partial void Onafn_inbound_working_quantityChanging(System.Nullable<long> value);
    partial void Onafn_inbound_working_quantityChanged();
    partial void Onafn_inbound_shipped_quantityChanging(System.Nullable<long> value);
    partial void Onafn_inbound_shipped_quantityChanged();
    partial void Onafn_inbound_receiving_quantityChanging(System.Nullable<long> value);
    partial void Onafn_inbound_receiving_quantityChanged();
    #endregion
		
		public UnsuppressedInventoryData()
		{
			this._Product = default(EntityRef<Product>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnsuppressedInventoryDataId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long UnsuppressedInventoryDataId
		{
			get
			{
				return this._UnsuppressedInventoryDataId;
			}
			set
			{
				if ((this._UnsuppressedInventoryDataId != value))
				{
					this.OnUnsuppressedInventoryDataIdChanging(value);
					this.SendPropertyChanging();
					this._UnsuppressedInventoryDataId = value;
					this.SendPropertyChanged("UnsuppressedInventoryDataId");
					this.OnUnsuppressedInventoryDataIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sku", DbType="NVarChar(50)")]
		public string sku
		{
			get
			{
				return this._sku;
			}
			set
			{
				if ((this._sku != value))
				{
					this.OnskuChanging(value);
					this.SendPropertyChanging();
					this._sku = value;
					this.SendPropertyChanged("sku");
					this.OnskuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fnsku", DbType="NVarChar(50)")]
		public string fnsku
		{
			get
			{
				return this._fnsku;
			}
			set
			{
				if ((this._fnsku != value))
				{
					this.OnfnskuChanging(value);
					this.SendPropertyChanging();
					this._fnsku = value;
					this.SendPropertyChanged("fnsku");
					this.OnfnskuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_asin", DbType="NVarChar(50)")]
		public string asin
		{
			get
			{
				return this._asin;
			}
			set
			{
				if ((this._asin != value))
				{
					if (this._Product.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnasinChanging(value);
					this.SendPropertyChanging();
					this._asin = value;
					this.SendPropertyChanged("asin");
					this.OnasinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[product-name]", Storage="_product_name", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string product_name
		{
			get
			{
				return this._product_name;
			}
			set
			{
				if ((this._product_name != value))
				{
					this.Onproduct_nameChanging(value);
					this.SendPropertyChanging();
					this._product_name = value;
					this.SendPropertyChanged("product_name");
					this.Onproduct_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_condition", DbType="NVarChar(20)")]
		public string condition
		{
			get
			{
				return this._condition;
			}
			set
			{
				if ((this._condition != value))
				{
					this.OnconditionChanging(value);
					this.SendPropertyChanging();
					this._condition = value;
					this.SendPropertyChanged("condition");
					this.OnconditionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[your-price]", Storage="_your_price", DbType="Money")]
		public System.Nullable<decimal> your_price
		{
			get
			{
				return this._your_price;
			}
			set
			{
				if ((this._your_price != value))
				{
					this.Onyour_priceChanging(value);
					this.SendPropertyChanging();
					this._your_price = value;
					this.SendPropertyChanged("your_price");
					this.Onyour_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[mfn-listing-exists]", Storage="_mfn_listing_exists", DbType="NVarChar(20)")]
		public string mfn_listing_exists
		{
			get
			{
				return this._mfn_listing_exists;
			}
			set
			{
				if ((this._mfn_listing_exists != value))
				{
					this.Onmfn_listing_existsChanging(value);
					this.SendPropertyChanging();
					this._mfn_listing_exists = value;
					this.SendPropertyChanged("mfn_listing_exists");
					this.Onmfn_listing_existsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[mfn-fulfillable-quantity]", Storage="_mfn_fulfillable_quantity", DbType="BigInt")]
		public System.Nullable<long> mfn_fulfillable_quantity
		{
			get
			{
				return this._mfn_fulfillable_quantity;
			}
			set
			{
				if ((this._mfn_fulfillable_quantity != value))
				{
					this.Onmfn_fulfillable_quantityChanging(value);
					this.SendPropertyChanging();
					this._mfn_fulfillable_quantity = value;
					this.SendPropertyChanged("mfn_fulfillable_quantity");
					this.Onmfn_fulfillable_quantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[afn-listing-exists]", Storage="_afn_listing_exists", DbType="NVarChar(20)")]
		public string afn_listing_exists
		{
			get
			{
				return this._afn_listing_exists;
			}
			set
			{
				if ((this._afn_listing_exists != value))
				{
					this.Onafn_listing_existsChanging(value);
					this.SendPropertyChanging();
					this._afn_listing_exists = value;
					this.SendPropertyChanged("afn_listing_exists");
					this.Onafn_listing_existsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[afn-warehouse-quantity]", Storage="_afn_warehouse_quantity", DbType="BigInt")]
		public System.Nullable<long> afn_warehouse_quantity
		{
			get
			{
				return this._afn_warehouse_quantity;
			}
			set
			{
				if ((this._afn_warehouse_quantity != value))
				{
					this.Onafn_warehouse_quantityChanging(value);
					this.SendPropertyChanging();
					this._afn_warehouse_quantity = value;
					this.SendPropertyChanged("afn_warehouse_quantity");
					this.Onafn_warehouse_quantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[afn-fulfillable-quantity]", Storage="_afn_fulfillable_quantity", DbType="BigInt")]
		public System.Nullable<long> afn_fulfillable_quantity
		{
			get
			{
				return this._afn_fulfillable_quantity;
			}
			set
			{
				if ((this._afn_fulfillable_quantity != value))
				{
					this.Onafn_fulfillable_quantityChanging(value);
					this.SendPropertyChanging();
					this._afn_fulfillable_quantity = value;
					this.SendPropertyChanged("afn_fulfillable_quantity");
					this.Onafn_fulfillable_quantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[afn-unsellable-quantity]", Storage="_afn_unsellable_quantity", DbType="BigInt")]
		public System.Nullable<long> afn_unsellable_quantity
		{
			get
			{
				return this._afn_unsellable_quantity;
			}
			set
			{
				if ((this._afn_unsellable_quantity != value))
				{
					this.Onafn_unsellable_quantityChanging(value);
					this.SendPropertyChanging();
					this._afn_unsellable_quantity = value;
					this.SendPropertyChanged("afn_unsellable_quantity");
					this.Onafn_unsellable_quantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[afn-reserved-quantity]", Storage="_afn_reserved_quantity", DbType="BigInt")]
		public System.Nullable<long> afn_reserved_quantity
		{
			get
			{
				return this._afn_reserved_quantity;
			}
			set
			{
				if ((this._afn_reserved_quantity != value))
				{
					this.Onafn_reserved_quantityChanging(value);
					this.SendPropertyChanging();
					this._afn_reserved_quantity = value;
					this.SendPropertyChanged("afn_reserved_quantity");
					this.Onafn_reserved_quantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[afn-total-quantity]", Storage="_afn_total_quantity", DbType="BigInt")]
		public System.Nullable<long> afn_total_quantity
		{
			get
			{
				return this._afn_total_quantity;
			}
			set
			{
				if ((this._afn_total_quantity != value))
				{
					this.Onafn_total_quantityChanging(value);
					this.SendPropertyChanging();
					this._afn_total_quantity = value;
					this.SendPropertyChanged("afn_total_quantity");
					this.Onafn_total_quantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[per-unit-volume]", Storage="_per_unit_volume", DbType="Decimal(18,9)")]
		public System.Nullable<decimal> per_unit_volume
		{
			get
			{
				return this._per_unit_volume;
			}
			set
			{
				if ((this._per_unit_volume != value))
				{
					this.Onper_unit_volumeChanging(value);
					this.SendPropertyChanging();
					this._per_unit_volume = value;
					this.SendPropertyChanged("per_unit_volume");
					this.Onper_unit_volumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[afn-inbound-working-quantity]", Storage="_afn_inbound_working_quantity", DbType="BigInt")]
		public System.Nullable<long> afn_inbound_working_quantity
		{
			get
			{
				return this._afn_inbound_working_quantity;
			}
			set
			{
				if ((this._afn_inbound_working_quantity != value))
				{
					this.Onafn_inbound_working_quantityChanging(value);
					this.SendPropertyChanging();
					this._afn_inbound_working_quantity = value;
					this.SendPropertyChanged("afn_inbound_working_quantity");
					this.Onafn_inbound_working_quantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[afn-inbound-shipped-quantity]", Storage="_afn_inbound_shipped_quantity", DbType="BigInt")]
		public System.Nullable<long> afn_inbound_shipped_quantity
		{
			get
			{
				return this._afn_inbound_shipped_quantity;
			}
			set
			{
				if ((this._afn_inbound_shipped_quantity != value))
				{
					this.Onafn_inbound_shipped_quantityChanging(value);
					this.SendPropertyChanging();
					this._afn_inbound_shipped_quantity = value;
					this.SendPropertyChanged("afn_inbound_shipped_quantity");
					this.Onafn_inbound_shipped_quantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[afn-inbound-receiving-quantity]", Storage="_afn_inbound_receiving_quantity", DbType="BigInt")]
		public System.Nullable<long> afn_inbound_receiving_quantity
		{
			get
			{
				return this._afn_inbound_receiving_quantity;
			}
			set
			{
				if ((this._afn_inbound_receiving_quantity != value))
				{
					this.Onafn_inbound_receiving_quantityChanging(value);
					this.SendPropertyChanging();
					this._afn_inbound_receiving_quantity = value;
					this.SendPropertyChanged("afn_inbound_receiving_quantity");
					this.Onafn_inbound_receiving_quantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Product_UnsuppressedInventoryData", Storage="_Product", ThisKey="asin", OtherKey="ASIN", IsForeignKey=true)]
		public Product Product
		{
			get
			{
				return this._Product.Entity;
			}
			set
			{
				Product previousValue = this._Product.Entity;
				if (((previousValue != value) 
							|| (this._Product.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Product.Entity = null;
						previousValue.UnsuppressedInventoryDatas.Remove(this);
					}
					this._Product.Entity = value;
					if ((value != null))
					{
						value.UnsuppressedInventoryDatas.Add(this);
						this._asin = value.ASIN;
					}
					else
					{
						this._asin = default(string);
					}
					this.SendPropertyChanged("Product");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FeePreviewData")]
	public partial class FeePreviewData : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _FeePreviewId;
		
		private System.DateTime _Date;
		
		private string _sku;
		
		private string _fnsku;
		
		private string _asin;
		
		private string _product_name;
		
		private string _product_group;
		
		private string _brand;
		
		private string _fulfilled_by;
		
		private decimal _your_price;
		
		private decimal _sales_price;
		
		private decimal _longest_side;
		
		private decimal _median_side;
		
		private decimal _shortest_side;
		
		private decimal _length_and_girth;
		
		private string _unit_of_dimension;
		
		private decimal _item_package_weight;
		
		private string _unit_of_weight;
		
		private string _product_size_tier;
		
		private string _currency;
		
		private decimal _estimated_fee;
		
		private decimal _estimated_referral_fee_per_unit;
		
		private decimal _estimated_variable_closing_fee;
		
		private decimal _estimated_order_handling_fee_per_order;
		
		private decimal _estimated_pick_pack_fee_per_unit;
		
		private decimal _estimated_weight_handling_fee_per_unit;
		
		private EntityRef<Product> _Product;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFeePreviewIdChanging(long value);
    partial void OnFeePreviewIdChanged();
    partial void OnDateChanging(System.DateTime value);
    partial void OnDateChanged();
    partial void OnskuChanging(string value);
    partial void OnskuChanged();
    partial void OnfnskuChanging(string value);
    partial void OnfnskuChanged();
    partial void OnasinChanging(string value);
    partial void OnasinChanged();
    partial void Onproduct_nameChanging(string value);
    partial void Onproduct_nameChanged();
    partial void Onproduct_groupChanging(string value);
    partial void Onproduct_groupChanged();
    partial void OnbrandChanging(string value);
    partial void OnbrandChanged();
    partial void Onfulfilled_byChanging(string value);
    partial void Onfulfilled_byChanged();
    partial void Onyour_priceChanging(decimal value);
    partial void Onyour_priceChanged();
    partial void Onsales_priceChanging(decimal value);
    partial void Onsales_priceChanged();
    partial void Onlongest_sideChanging(decimal value);
    partial void Onlongest_sideChanged();
    partial void Onmedian_sideChanging(decimal value);
    partial void Onmedian_sideChanged();
    partial void Onshortest_sideChanging(decimal value);
    partial void Onshortest_sideChanged();
    partial void Onlength_and_girthChanging(decimal value);
    partial void Onlength_and_girthChanged();
    partial void Onunit_of_dimensionChanging(string value);
    partial void Onunit_of_dimensionChanged();
    partial void Onitem_package_weightChanging(decimal value);
    partial void Onitem_package_weightChanged();
    partial void Onunit_of_weightChanging(string value);
    partial void Onunit_of_weightChanged();
    partial void Onproduct_size_tierChanging(string value);
    partial void Onproduct_size_tierChanged();
    partial void OncurrencyChanging(string value);
    partial void OncurrencyChanged();
    partial void Onestimated_feeChanging(decimal value);
    partial void Onestimated_feeChanged();
    partial void Onestimated_referral_fee_per_unitChanging(decimal value);
    partial void Onestimated_referral_fee_per_unitChanged();
    partial void Onestimated_variable_closing_feeChanging(decimal value);
    partial void Onestimated_variable_closing_feeChanged();
    partial void Onestimated_order_handling_fee_per_orderChanging(decimal value);
    partial void Onestimated_order_handling_fee_per_orderChanged();
    partial void Onestimated_pick_pack_fee_per_unitChanging(decimal value);
    partial void Onestimated_pick_pack_fee_per_unitChanged();
    partial void Onestimated_weight_handling_fee_per_unitChanging(decimal value);
    partial void Onestimated_weight_handling_fee_per_unitChanged();
    #endregion
		
		public FeePreviewData()
		{
			this._Product = default(EntityRef<Product>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeePreviewId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long FeePreviewId
		{
			get
			{
				return this._FeePreviewId;
			}
			set
			{
				if ((this._FeePreviewId != value))
				{
					this.OnFeePreviewIdChanging(value);
					this.SendPropertyChanging();
					this._FeePreviewId = value;
					this.SendPropertyChanged("FeePreviewId");
					this.OnFeePreviewIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="Date NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sku", DbType="NVarChar(50)")]
		public string sku
		{
			get
			{
				return this._sku;
			}
			set
			{
				if ((this._sku != value))
				{
					this.OnskuChanging(value);
					this.SendPropertyChanging();
					this._sku = value;
					this.SendPropertyChanged("sku");
					this.OnskuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fnsku", DbType="NVarChar(50)")]
		public string fnsku
		{
			get
			{
				return this._fnsku;
			}
			set
			{
				if ((this._fnsku != value))
				{
					this.OnfnskuChanging(value);
					this.SendPropertyChanging();
					this._fnsku = value;
					this.SendPropertyChanged("fnsku");
					this.OnfnskuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_asin", DbType="NVarChar(50)")]
		public string asin
		{
			get
			{
				return this._asin;
			}
			set
			{
				if ((this._asin != value))
				{
					if (this._Product.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnasinChanging(value);
					this.SendPropertyChanging();
					this._asin = value;
					this.SendPropertyChanged("asin");
					this.OnasinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[product-name]", Storage="_product_name", DbType="NVarChar(255)")]
		public string product_name
		{
			get
			{
				return this._product_name;
			}
			set
			{
				if ((this._product_name != value))
				{
					this.Onproduct_nameChanging(value);
					this.SendPropertyChanging();
					this._product_name = value;
					this.SendPropertyChanged("product_name");
					this.Onproduct_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[product-group]", Storage="_product_group", DbType="NVarChar(255)")]
		public string product_group
		{
			get
			{
				return this._product_group;
			}
			set
			{
				if ((this._product_group != value))
				{
					this.Onproduct_groupChanging(value);
					this.SendPropertyChanging();
					this._product_group = value;
					this.SendPropertyChanged("product_group");
					this.Onproduct_groupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_brand", DbType="NVarChar(255)")]
		public string brand
		{
			get
			{
				return this._brand;
			}
			set
			{
				if ((this._brand != value))
				{
					this.OnbrandChanging(value);
					this.SendPropertyChanging();
					this._brand = value;
					this.SendPropertyChanged("brand");
					this.OnbrandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[fulfilled-by]", Storage="_fulfilled_by", DbType="NVarChar(255)")]
		public string fulfilled_by
		{
			get
			{
				return this._fulfilled_by;
			}
			set
			{
				if ((this._fulfilled_by != value))
				{
					this.Onfulfilled_byChanging(value);
					this.SendPropertyChanging();
					this._fulfilled_by = value;
					this.SendPropertyChanged("fulfilled_by");
					this.Onfulfilled_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[your-price]", Storage="_your_price", DbType="Decimal(18,2) NOT NULL")]
		public decimal your_price
		{
			get
			{
				return this._your_price;
			}
			set
			{
				if ((this._your_price != value))
				{
					this.Onyour_priceChanging(value);
					this.SendPropertyChanging();
					this._your_price = value;
					this.SendPropertyChanged("your_price");
					this.Onyour_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[sales-price]", Storage="_sales_price", DbType="Decimal(18,2) NOT NULL")]
		public decimal sales_price
		{
			get
			{
				return this._sales_price;
			}
			set
			{
				if ((this._sales_price != value))
				{
					this.Onsales_priceChanging(value);
					this.SendPropertyChanging();
					this._sales_price = value;
					this.SendPropertyChanged("sales_price");
					this.Onsales_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[longest-side]", Storage="_longest_side", DbType="Decimal(18,2) NOT NULL")]
		public decimal longest_side
		{
			get
			{
				return this._longest_side;
			}
			set
			{
				if ((this._longest_side != value))
				{
					this.Onlongest_sideChanging(value);
					this.SendPropertyChanging();
					this._longest_side = value;
					this.SendPropertyChanged("longest_side");
					this.Onlongest_sideChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[median-side]", Storage="_median_side", DbType="Decimal(18,2) NOT NULL")]
		public decimal median_side
		{
			get
			{
				return this._median_side;
			}
			set
			{
				if ((this._median_side != value))
				{
					this.Onmedian_sideChanging(value);
					this.SendPropertyChanging();
					this._median_side = value;
					this.SendPropertyChanged("median_side");
					this.Onmedian_sideChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[shortest-side]", Storage="_shortest_side", DbType="Decimal(18,2) NOT NULL")]
		public decimal shortest_side
		{
			get
			{
				return this._shortest_side;
			}
			set
			{
				if ((this._shortest_side != value))
				{
					this.Onshortest_sideChanging(value);
					this.SendPropertyChanging();
					this._shortest_side = value;
					this.SendPropertyChanged("shortest_side");
					this.Onshortest_sideChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[length-and-girth]", Storage="_length_and_girth", DbType="Decimal(18,2) NOT NULL")]
		public decimal length_and_girth
		{
			get
			{
				return this._length_and_girth;
			}
			set
			{
				if ((this._length_and_girth != value))
				{
					this.Onlength_and_girthChanging(value);
					this.SendPropertyChanging();
					this._length_and_girth = value;
					this.SendPropertyChanged("length_and_girth");
					this.Onlength_and_girthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[unit-of-dimension]", Storage="_unit_of_dimension", DbType="NVarChar(255)")]
		public string unit_of_dimension
		{
			get
			{
				return this._unit_of_dimension;
			}
			set
			{
				if ((this._unit_of_dimension != value))
				{
					this.Onunit_of_dimensionChanging(value);
					this.SendPropertyChanging();
					this._unit_of_dimension = value;
					this.SendPropertyChanged("unit_of_dimension");
					this.Onunit_of_dimensionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[item-package-weight]", Storage="_item_package_weight", DbType="Decimal(18,2) NOT NULL")]
		public decimal item_package_weight
		{
			get
			{
				return this._item_package_weight;
			}
			set
			{
				if ((this._item_package_weight != value))
				{
					this.Onitem_package_weightChanging(value);
					this.SendPropertyChanging();
					this._item_package_weight = value;
					this.SendPropertyChanged("item_package_weight");
					this.Onitem_package_weightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[unit-of-weight]", Storage="_unit_of_weight", DbType="NVarChar(255)")]
		public string unit_of_weight
		{
			get
			{
				return this._unit_of_weight;
			}
			set
			{
				if ((this._unit_of_weight != value))
				{
					this.Onunit_of_weightChanging(value);
					this.SendPropertyChanging();
					this._unit_of_weight = value;
					this.SendPropertyChanged("unit_of_weight");
					this.Onunit_of_weightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[product-size-tier]", Storage="_product_size_tier", DbType="NVarChar(255)")]
		public string product_size_tier
		{
			get
			{
				return this._product_size_tier;
			}
			set
			{
				if ((this._product_size_tier != value))
				{
					this.Onproduct_size_tierChanging(value);
					this.SendPropertyChanging();
					this._product_size_tier = value;
					this.SendPropertyChanged("product_size_tier");
					this.Onproduct_size_tierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_currency", DbType="NVarChar(255)")]
		public string currency
		{
			get
			{
				return this._currency;
			}
			set
			{
				if ((this._currency != value))
				{
					this.OncurrencyChanging(value);
					this.SendPropertyChanging();
					this._currency = value;
					this.SendPropertyChanged("currency");
					this.OncurrencyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[estimated-fee]", Storage="_estimated_fee", DbType="Decimal(18,2) NOT NULL")]
		public decimal estimated_fee
		{
			get
			{
				return this._estimated_fee;
			}
			set
			{
				if ((this._estimated_fee != value))
				{
					this.Onestimated_feeChanging(value);
					this.SendPropertyChanging();
					this._estimated_fee = value;
					this.SendPropertyChanged("estimated_fee");
					this.Onestimated_feeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[estimated-referral-fee-per-unit]", Storage="_estimated_referral_fee_per_unit", DbType="Decimal(18,2) NOT NULL")]
		public decimal estimated_referral_fee_per_unit
		{
			get
			{
				return this._estimated_referral_fee_per_unit;
			}
			set
			{
				if ((this._estimated_referral_fee_per_unit != value))
				{
					this.Onestimated_referral_fee_per_unitChanging(value);
					this.SendPropertyChanging();
					this._estimated_referral_fee_per_unit = value;
					this.SendPropertyChanged("estimated_referral_fee_per_unit");
					this.Onestimated_referral_fee_per_unitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[estimated-variable-closing-fee]", Storage="_estimated_variable_closing_fee", DbType="Decimal(18,2) NOT NULL")]
		public decimal estimated_variable_closing_fee
		{
			get
			{
				return this._estimated_variable_closing_fee;
			}
			set
			{
				if ((this._estimated_variable_closing_fee != value))
				{
					this.Onestimated_variable_closing_feeChanging(value);
					this.SendPropertyChanging();
					this._estimated_variable_closing_fee = value;
					this.SendPropertyChanged("estimated_variable_closing_fee");
					this.Onestimated_variable_closing_feeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[estimated-order-handling-fee-per-order]", Storage="_estimated_order_handling_fee_per_order", DbType="Decimal(18,2) NOT NULL")]
		public decimal estimated_order_handling_fee_per_order
		{
			get
			{
				return this._estimated_order_handling_fee_per_order;
			}
			set
			{
				if ((this._estimated_order_handling_fee_per_order != value))
				{
					this.Onestimated_order_handling_fee_per_orderChanging(value);
					this.SendPropertyChanging();
					this._estimated_order_handling_fee_per_order = value;
					this.SendPropertyChanged("estimated_order_handling_fee_per_order");
					this.Onestimated_order_handling_fee_per_orderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[estimated-pick-pack-fee-per-unit]", Storage="_estimated_pick_pack_fee_per_unit", DbType="Decimal(18,2) NOT NULL")]
		public decimal estimated_pick_pack_fee_per_unit
		{
			get
			{
				return this._estimated_pick_pack_fee_per_unit;
			}
			set
			{
				if ((this._estimated_pick_pack_fee_per_unit != value))
				{
					this.Onestimated_pick_pack_fee_per_unitChanging(value);
					this.SendPropertyChanging();
					this._estimated_pick_pack_fee_per_unit = value;
					this.SendPropertyChanged("estimated_pick_pack_fee_per_unit");
					this.Onestimated_pick_pack_fee_per_unitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[estimated-weight-handling-fee-per-unit]", Storage="_estimated_weight_handling_fee_per_unit", DbType="Decimal(18,2) NOT NULL")]
		public decimal estimated_weight_handling_fee_per_unit
		{
			get
			{
				return this._estimated_weight_handling_fee_per_unit;
			}
			set
			{
				if ((this._estimated_weight_handling_fee_per_unit != value))
				{
					this.Onestimated_weight_handling_fee_per_unitChanging(value);
					this.SendPropertyChanging();
					this._estimated_weight_handling_fee_per_unit = value;
					this.SendPropertyChanged("estimated_weight_handling_fee_per_unit");
					this.Onestimated_weight_handling_fee_per_unitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Product_FeePreviewData", Storage="_Product", ThisKey="asin", OtherKey="ASIN", IsForeignKey=true)]
		public Product Product
		{
			get
			{
				return this._Product.Entity;
			}
			set
			{
				Product previousValue = this._Product.Entity;
				if (((previousValue != value) 
							|| (this._Product.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Product.Entity = null;
						previousValue.FeePreviewDatas.Remove(this);
					}
					this._Product.Entity = value;
					if ((value != null))
					{
						value.FeePreviewDatas.Add(this);
						this._asin = value.ASIN;
					}
					else
					{
						this._asin = default(string);
					}
					this.SendPropertyChanged("Product");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PriceHistory")]
	public partial class PriceHistory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _PriceHistoryId;
		
		private decimal _NewPrice;
		
		private System.DateTime _TimeStamp;
		
		private string _ASIN;
		
		private System.Nullable<decimal> _BreakEvenPrice;
		
		private System.Nullable<decimal> _MyOfferPriceInNotification;
		
		private System.Nullable<decimal> _AmazonsOfferPriceInNotification;
		
		private System.Nullable<decimal> _LowestFbaOfferPriceInNotification;
		
		private System.Nullable<decimal> _LowestNonFbaOfferPriceInNotification;
		
		private System.Nullable<System.DateTime> _LastNotificationPublishDateTime;
		
		private System.Nullable<decimal> _MyPriceFromProductsApi;
		
		private string _ListingOffersSource;
		
		private EntitySet<Product> _Products;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPriceHistoryIdChanging(long value);
    partial void OnPriceHistoryIdChanged();
    partial void OnNewPriceChanging(decimal value);
    partial void OnNewPriceChanged();
    partial void OnTimeStampChanging(System.DateTime value);
    partial void OnTimeStampChanged();
    partial void OnASINChanging(string value);
    partial void OnASINChanged();
    partial void OnBreakEvenPriceChanging(System.Nullable<decimal> value);
    partial void OnBreakEvenPriceChanged();
    partial void OnMyOfferPriceInNotificationChanging(System.Nullable<decimal> value);
    partial void OnMyOfferPriceInNotificationChanged();
    partial void OnAmazonsOfferPriceInNotificationChanging(System.Nullable<decimal> value);
    partial void OnAmazonsOfferPriceInNotificationChanged();
    partial void OnLowestFbaOfferPriceInNotificationChanging(System.Nullable<decimal> value);
    partial void OnLowestFbaOfferPriceInNotificationChanged();
    partial void OnLowestNonFbaOfferPriceInNotificationChanging(System.Nullable<decimal> value);
    partial void OnLowestNonFbaOfferPriceInNotificationChanged();
    partial void OnLastNotificationPublishDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnLastNotificationPublishDateTimeChanged();
    partial void OnMyPriceFromProductsApiChanging(System.Nullable<decimal> value);
    partial void OnMyPriceFromProductsApiChanged();
    partial void OnListingOffersSourceChanging(string value);
    partial void OnListingOffersSourceChanged();
    #endregion
		
		public PriceHistory()
		{
			this._Products = new EntitySet<Product>(new Action<Product>(this.attach_Products), new Action<Product>(this.detach_Products));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceHistoryId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long PriceHistoryId
		{
			get
			{
				return this._PriceHistoryId;
			}
			set
			{
				if ((this._PriceHistoryId != value))
				{
					this.OnPriceHistoryIdChanging(value);
					this.SendPropertyChanging();
					this._PriceHistoryId = value;
					this.SendPropertyChanged("PriceHistoryId");
					this.OnPriceHistoryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewPrice", DbType="Decimal(10,2) NOT NULL")]
		public decimal NewPrice
		{
			get
			{
				return this._NewPrice;
			}
			set
			{
				if ((this._NewPrice != value))
				{
					this.OnNewPriceChanging(value);
					this.SendPropertyChanging();
					this._NewPrice = value;
					this.SendPropertyChanged("NewPrice");
					this.OnNewPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeStamp", DbType="DateTime2 NOT NULL")]
		public System.DateTime TimeStamp
		{
			get
			{
				return this._TimeStamp;
			}
			set
			{
				if ((this._TimeStamp != value))
				{
					this.OnTimeStampChanging(value);
					this.SendPropertyChanging();
					this._TimeStamp = value;
					this.SendPropertyChanged("TimeStamp");
					this.OnTimeStampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ASIN", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ASIN
		{
			get
			{
				return this._ASIN;
			}
			set
			{
				if ((this._ASIN != value))
				{
					this.OnASINChanging(value);
					this.SendPropertyChanging();
					this._ASIN = value;
					this.SendPropertyChanged("ASIN");
					this.OnASINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BreakEvenPrice", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> BreakEvenPrice
		{
			get
			{
				return this._BreakEvenPrice;
			}
			set
			{
				if ((this._BreakEvenPrice != value))
				{
					this.OnBreakEvenPriceChanging(value);
					this.SendPropertyChanging();
					this._BreakEvenPrice = value;
					this.SendPropertyChanged("BreakEvenPrice");
					this.OnBreakEvenPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MyOfferPriceInNotification", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> MyOfferPriceInNotification
		{
			get
			{
				return this._MyOfferPriceInNotification;
			}
			set
			{
				if ((this._MyOfferPriceInNotification != value))
				{
					this.OnMyOfferPriceInNotificationChanging(value);
					this.SendPropertyChanging();
					this._MyOfferPriceInNotification = value;
					this.SendPropertyChanged("MyOfferPriceInNotification");
					this.OnMyOfferPriceInNotificationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AmazonsOfferPriceInNotification", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> AmazonsOfferPriceInNotification
		{
			get
			{
				return this._AmazonsOfferPriceInNotification;
			}
			set
			{
				if ((this._AmazonsOfferPriceInNotification != value))
				{
					this.OnAmazonsOfferPriceInNotificationChanging(value);
					this.SendPropertyChanging();
					this._AmazonsOfferPriceInNotification = value;
					this.SendPropertyChanged("AmazonsOfferPriceInNotification");
					this.OnAmazonsOfferPriceInNotificationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LowestFbaOfferPriceInNotification", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> LowestFbaOfferPriceInNotification
		{
			get
			{
				return this._LowestFbaOfferPriceInNotification;
			}
			set
			{
				if ((this._LowestFbaOfferPriceInNotification != value))
				{
					this.OnLowestFbaOfferPriceInNotificationChanging(value);
					this.SendPropertyChanging();
					this._LowestFbaOfferPriceInNotification = value;
					this.SendPropertyChanged("LowestFbaOfferPriceInNotification");
					this.OnLowestFbaOfferPriceInNotificationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LowestNonFbaOfferPriceInNotification", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> LowestNonFbaOfferPriceInNotification
		{
			get
			{
				return this._LowestNonFbaOfferPriceInNotification;
			}
			set
			{
				if ((this._LowestNonFbaOfferPriceInNotification != value))
				{
					this.OnLowestNonFbaOfferPriceInNotificationChanging(value);
					this.SendPropertyChanging();
					this._LowestNonFbaOfferPriceInNotification = value;
					this.SendPropertyChanged("LowestNonFbaOfferPriceInNotification");
					this.OnLowestNonFbaOfferPriceInNotificationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastNotificationPublishDateTime", DbType="DateTime2")]
		public System.Nullable<System.DateTime> LastNotificationPublishDateTime
		{
			get
			{
				return this._LastNotificationPublishDateTime;
			}
			set
			{
				if ((this._LastNotificationPublishDateTime != value))
				{
					this.OnLastNotificationPublishDateTimeChanging(value);
					this.SendPropertyChanging();
					this._LastNotificationPublishDateTime = value;
					this.SendPropertyChanged("LastNotificationPublishDateTime");
					this.OnLastNotificationPublishDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MyPriceFromProductsApi", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> MyPriceFromProductsApi
		{
			get
			{
				return this._MyPriceFromProductsApi;
			}
			set
			{
				if ((this._MyPriceFromProductsApi != value))
				{
					this.OnMyPriceFromProductsApiChanging(value);
					this.SendPropertyChanging();
					this._MyPriceFromProductsApi = value;
					this.SendPropertyChanged("MyPriceFromProductsApi");
					this.OnMyPriceFromProductsApiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ListingOffersSource", DbType="NVarChar(30)")]
		public string ListingOffersSource
		{
			get
			{
				return this._ListingOffersSource;
			}
			set
			{
				if ((this._ListingOffersSource != value))
				{
					this.OnListingOffersSourceChanging(value);
					this.SendPropertyChanging();
					this._ListingOffersSource = value;
					this.SendPropertyChanged("ListingOffersSource");
					this.OnListingOffersSourceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PriceHistory_Product", Storage="_Products", ThisKey="ASIN", OtherKey="ASIN")]
		public EntitySet<Product> Products
		{
			get
			{
				return this._Products;
			}
			set
			{
				this._Products.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Products(Product entity)
		{
			this.SendPropertyChanging();
			entity.PriceHistory = this;
		}
		
		private void detach_Products(Product entity)
		{
			this.SendPropertyChanging();
			entity.PriceHistory = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ListingOffersLog")]
	public partial class ListingOffersLog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _NotificationLogId;
		
		private string _ASIN;
		
		private System.DateTime _PublishDateTime;
		
		private System.Nullable<decimal> _LowestFbaPrice;
		
		private System.Nullable<decimal> _LowestNonFbaPrice;
		
		private System.Nullable<decimal> _OurPrice;
		
		private string _ListingOffersSource;
		
		private System.Nullable<int> _BuyBoxWinnerSellerType;
		
		private System.Nullable<decimal> _BuyBoxPrice;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNotificationLogIdChanging(long value);
    partial void OnNotificationLogIdChanged();
    partial void OnASINChanging(string value);
    partial void OnASINChanged();
    partial void OnPublishDateTimeChanging(System.DateTime value);
    partial void OnPublishDateTimeChanged();
    partial void OnLowestFbaPriceChanging(System.Nullable<decimal> value);
    partial void OnLowestFbaPriceChanged();
    partial void OnLowestNonFbaPriceChanging(System.Nullable<decimal> value);
    partial void OnLowestNonFbaPriceChanged();
    partial void OnOurPriceChanging(System.Nullable<decimal> value);
    partial void OnOurPriceChanged();
    partial void OnListingOffersSourceChanging(string value);
    partial void OnListingOffersSourceChanged();
    partial void OnBuyBoxWinnerSellerTypeChanging(System.Nullable<int> value);
    partial void OnBuyBoxWinnerSellerTypeChanged();
    partial void OnBuyBoxPriceChanging(System.Nullable<decimal> value);
    partial void OnBuyBoxPriceChanged();
    #endregion
		
		public ListingOffersLog()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NotificationLogId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long NotificationLogId
		{
			get
			{
				return this._NotificationLogId;
			}
			set
			{
				if ((this._NotificationLogId != value))
				{
					this.OnNotificationLogIdChanging(value);
					this.SendPropertyChanging();
					this._NotificationLogId = value;
					this.SendPropertyChanged("NotificationLogId");
					this.OnNotificationLogIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ASIN", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string ASIN
		{
			get
			{
				return this._ASIN;
			}
			set
			{
				if ((this._ASIN != value))
				{
					this.OnASINChanging(value);
					this.SendPropertyChanging();
					this._ASIN = value;
					this.SendPropertyChanged("ASIN");
					this.OnASINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PublishDateTime", DbType="DateTime2 NOT NULL")]
		public System.DateTime PublishDateTime
		{
			get
			{
				return this._PublishDateTime;
			}
			set
			{
				if ((this._PublishDateTime != value))
				{
					this.OnPublishDateTimeChanging(value);
					this.SendPropertyChanging();
					this._PublishDateTime = value;
					this.SendPropertyChanged("PublishDateTime");
					this.OnPublishDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LowestFbaPrice", DbType="Money")]
		public System.Nullable<decimal> LowestFbaPrice
		{
			get
			{
				return this._LowestFbaPrice;
			}
			set
			{
				if ((this._LowestFbaPrice != value))
				{
					this.OnLowestFbaPriceChanging(value);
					this.SendPropertyChanging();
					this._LowestFbaPrice = value;
					this.SendPropertyChanged("LowestFbaPrice");
					this.OnLowestFbaPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LowestNonFbaPrice", DbType="Money")]
		public System.Nullable<decimal> LowestNonFbaPrice
		{
			get
			{
				return this._LowestNonFbaPrice;
			}
			set
			{
				if ((this._LowestNonFbaPrice != value))
				{
					this.OnLowestNonFbaPriceChanging(value);
					this.SendPropertyChanging();
					this._LowestNonFbaPrice = value;
					this.SendPropertyChanged("LowestNonFbaPrice");
					this.OnLowestNonFbaPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OurPrice", DbType="Money")]
		public System.Nullable<decimal> OurPrice
		{
			get
			{
				return this._OurPrice;
			}
			set
			{
				if ((this._OurPrice != value))
				{
					this.OnOurPriceChanging(value);
					this.SendPropertyChanging();
					this._OurPrice = value;
					this.SendPropertyChanged("OurPrice");
					this.OnOurPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ListingOffersSource", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string ListingOffersSource
		{
			get
			{
				return this._ListingOffersSource;
			}
			set
			{
				if ((this._ListingOffersSource != value))
				{
					this.OnListingOffersSourceChanging(value);
					this.SendPropertyChanging();
					this._ListingOffersSource = value;
					this.SendPropertyChanged("ListingOffersSource");
					this.OnListingOffersSourceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuyBoxWinnerSellerType", DbType="Int")]
		public System.Nullable<int> BuyBoxWinnerSellerType
		{
			get
			{
				return this._BuyBoxWinnerSellerType;
			}
			set
			{
				if ((this._BuyBoxWinnerSellerType != value))
				{
					this.OnBuyBoxWinnerSellerTypeChanging(value);
					this.SendPropertyChanging();
					this._BuyBoxWinnerSellerType = value;
					this.SendPropertyChanged("BuyBoxWinnerSellerType");
					this.OnBuyBoxWinnerSellerTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuyBoxPrice", DbType="Money")]
		public System.Nullable<decimal> BuyBoxPrice
		{
			get
			{
				return this._BuyBoxPrice;
			}
			set
			{
				if ((this._BuyBoxPrice != value))
				{
					this.OnBuyBoxPriceChanging(value);
					this.SendPropertyChanging();
					this._BuyBoxPrice = value;
					this.SendPropertyChanged("BuyBoxPrice");
					this.OnBuyBoxPriceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Products")]
	public partial class Product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ProductId;
		
		private System.DateTime _CreatedDate;
		
		private System.DateTime _ModifiedDate;
		
		private string _UPC;
		
		private string _Name;
		
		private System.Nullable<decimal> _Cost;
		
		private System.Nullable<decimal> _PromotionCost;
		
		private System.Nullable<decimal> _OverrideCost;
		
		private System.Nullable<decimal> _MAPPrice;
		
		private System.Nullable<decimal> _MinPrice;
		
		private System.Nullable<decimal> _MaxPrice;
		
		private System.Nullable<decimal> _BreakevenPrice;
		
		private System.Nullable<long> _QuantityInCase;
		
		private string _ASIN;
		
		private string _SKU;
		
		private string _ItemNumber;
		
		private int _ManufacturerId;
		
		private System.Nullable<decimal> _Length;
		
		private System.Nullable<decimal> _Width;
		
		private System.Nullable<decimal> _Height;
		
		private System.Nullable<decimal> _Weight;
		
		private bool _IsMAP;
		
		private bool _IsDiscontinued;
		
		private string _Notes;
		
		private EntitySet<AllOrdersData> _AllOrdersDatas;
		
		private EntitySet<UnsuppressedInventoryData> _UnsuppressedInventoryDatas;
		
		private EntitySet<FeePreviewData> _FeePreviewDatas;
		
		private EntityRef<Manufacturer> _Manufacturer;
		
		private EntityRef<PriceHistory> _PriceHistory;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProductIdChanging(long value);
    partial void OnProductIdChanged();
    partial void OnCreatedDateChanging(System.DateTime value);
    partial void OnCreatedDateChanged();
    partial void OnModifiedDateChanging(System.DateTime value);
    partial void OnModifiedDateChanged();
    partial void OnUPCChanging(string value);
    partial void OnUPCChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnCostChanging(System.Nullable<decimal> value);
    partial void OnCostChanged();
    partial void OnPromotionCostChanging(System.Nullable<decimal> value);
    partial void OnPromotionCostChanged();
    partial void OnOverrideCostChanging(System.Nullable<decimal> value);
    partial void OnOverrideCostChanged();
    partial void OnMAPPriceChanging(System.Nullable<decimal> value);
    partial void OnMAPPriceChanged();
    partial void OnMinPriceChanging(System.Nullable<decimal> value);
    partial void OnMinPriceChanged();
    partial void OnMaxPriceChanging(System.Nullable<decimal> value);
    partial void OnMaxPriceChanged();
    partial void OnBreakevenPriceChanging(System.Nullable<decimal> value);
    partial void OnBreakevenPriceChanged();
    partial void OnQuantityInCaseChanging(System.Nullable<long> value);
    partial void OnQuantityInCaseChanged();
    partial void OnASINChanging(string value);
    partial void OnASINChanged();
    partial void OnSKUChanging(string value);
    partial void OnSKUChanged();
    partial void OnItemNumberChanging(string value);
    partial void OnItemNumberChanged();
    partial void OnManufacturerIdChanging(int value);
    partial void OnManufacturerIdChanged();
    partial void OnLengthChanging(System.Nullable<decimal> value);
    partial void OnLengthChanged();
    partial void OnWidthChanging(System.Nullable<decimal> value);
    partial void OnWidthChanged();
    partial void OnHeightChanging(System.Nullable<decimal> value);
    partial void OnHeightChanged();
    partial void OnWeightChanging(System.Nullable<decimal> value);
    partial void OnWeightChanged();
    partial void OnIsMAPChanging(bool value);
    partial void OnIsMAPChanged();
    partial void OnIsDiscontinuedChanging(bool value);
    partial void OnIsDiscontinuedChanged();
    partial void OnNotesChanging(string value);
    partial void OnNotesChanged();
    #endregion
		
		public Product()
		{
			this._AllOrdersDatas = new EntitySet<AllOrdersData>(new Action<AllOrdersData>(this.attach_AllOrdersDatas), new Action<AllOrdersData>(this.detach_AllOrdersDatas));
			this._UnsuppressedInventoryDatas = new EntitySet<UnsuppressedInventoryData>(new Action<UnsuppressedInventoryData>(this.attach_UnsuppressedInventoryDatas), new Action<UnsuppressedInventoryData>(this.detach_UnsuppressedInventoryDatas));
			this._FeePreviewDatas = new EntitySet<FeePreviewData>(new Action<FeePreviewData>(this.attach_FeePreviewDatas), new Action<FeePreviewData>(this.detach_FeePreviewDatas));
			this._Manufacturer = default(EntityRef<Manufacturer>);
			this._PriceHistory = default(EntityRef<PriceHistory>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ProductId
		{
			get
			{
				return this._ProductId;
			}
			set
			{
				if ((this._ProductId != value))
				{
					this.OnProductIdChanging(value);
					this.SendPropertyChanging();
					this._ProductId = value;
					this.SendPropertyChanged("ProductId");
					this.OnProductIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime2 NOT NULL")]
		public System.DateTime CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this.OnCreatedDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedDate = value;
					this.SendPropertyChanged("CreatedDate");
					this.OnCreatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedDate", DbType="DateTime2 NOT NULL")]
		public System.DateTime ModifiedDate
		{
			get
			{
				return this._ModifiedDate;
			}
			set
			{
				if ((this._ModifiedDate != value))
				{
					this.OnModifiedDateChanging(value);
					this.SendPropertyChanging();
					this._ModifiedDate = value;
					this.SendPropertyChanged("ModifiedDate");
					this.OnModifiedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPC", DbType="NVarChar(20)")]
		public string UPC
		{
			get
			{
				return this._UPC;
			}
			set
			{
				if ((this._UPC != value))
				{
					this.OnUPCChanging(value);
					this.SendPropertyChanging();
					this._UPC = value;
					this.SendPropertyChanged("UPC");
					this.OnUPCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cost", DbType="Money")]
		public System.Nullable<decimal> Cost
		{
			get
			{
				return this._Cost;
			}
			set
			{
				if ((this._Cost != value))
				{
					this.OnCostChanging(value);
					this.SendPropertyChanging();
					this._Cost = value;
					this.SendPropertyChanged("Cost");
					this.OnCostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PromotionCost", DbType="Money")]
		public System.Nullable<decimal> PromotionCost
		{
			get
			{
				return this._PromotionCost;
			}
			set
			{
				if ((this._PromotionCost != value))
				{
					this.OnPromotionCostChanging(value);
					this.SendPropertyChanging();
					this._PromotionCost = value;
					this.SendPropertyChanged("PromotionCost");
					this.OnPromotionCostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OverrideCost", DbType="Money")]
		public System.Nullable<decimal> OverrideCost
		{
			get
			{
				return this._OverrideCost;
			}
			set
			{
				if ((this._OverrideCost != value))
				{
					this.OnOverrideCostChanging(value);
					this.SendPropertyChanging();
					this._OverrideCost = value;
					this.SendPropertyChanged("OverrideCost");
					this.OnOverrideCostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPPrice", DbType="Money")]
		public System.Nullable<decimal> MAPPrice
		{
			get
			{
				return this._MAPPrice;
			}
			set
			{
				if ((this._MAPPrice != value))
				{
					this.OnMAPPriceChanging(value);
					this.SendPropertyChanging();
					this._MAPPrice = value;
					this.SendPropertyChanged("MAPPrice");
					this.OnMAPPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinPrice", DbType="Money")]
		public System.Nullable<decimal> MinPrice
		{
			get
			{
				return this._MinPrice;
			}
			set
			{
				if ((this._MinPrice != value))
				{
					this.OnMinPriceChanging(value);
					this.SendPropertyChanging();
					this._MinPrice = value;
					this.SendPropertyChanged("MinPrice");
					this.OnMinPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxPrice", DbType="Money")]
		public System.Nullable<decimal> MaxPrice
		{
			get
			{
				return this._MaxPrice;
			}
			set
			{
				if ((this._MaxPrice != value))
				{
					this.OnMaxPriceChanging(value);
					this.SendPropertyChanging();
					this._MaxPrice = value;
					this.SendPropertyChanged("MaxPrice");
					this.OnMaxPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BreakevenPrice", DbType="Money")]
		public System.Nullable<decimal> BreakevenPrice
		{
			get
			{
				return this._BreakevenPrice;
			}
			set
			{
				if ((this._BreakevenPrice != value))
				{
					this.OnBreakevenPriceChanging(value);
					this.SendPropertyChanging();
					this._BreakevenPrice = value;
					this.SendPropertyChanged("BreakevenPrice");
					this.OnBreakevenPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuantityInCase", DbType="BigInt")]
		public System.Nullable<long> QuantityInCase
		{
			get
			{
				return this._QuantityInCase;
			}
			set
			{
				if ((this._QuantityInCase != value))
				{
					this.OnQuantityInCaseChanging(value);
					this.SendPropertyChanging();
					this._QuantityInCase = value;
					this.SendPropertyChanged("QuantityInCase");
					this.OnQuantityInCaseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ASIN", DbType="NVarChar(20)")]
		public string ASIN
		{
			get
			{
				return this._ASIN;
			}
			set
			{
				if ((this._ASIN != value))
				{
					if (this._PriceHistory.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnASINChanging(value);
					this.SendPropertyChanging();
					this._ASIN = value;
					this.SendPropertyChanged("ASIN");
					this.OnASINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SKU", DbType="NVarChar(20)")]
		public string SKU
		{
			get
			{
				return this._SKU;
			}
			set
			{
				if ((this._SKU != value))
				{
					this.OnSKUChanging(value);
					this.SendPropertyChanging();
					this._SKU = value;
					this.SendPropertyChanged("SKU");
					this.OnSKUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemNumber", DbType="NVarChar(255)")]
		public string ItemNumber
		{
			get
			{
				return this._ItemNumber;
			}
			set
			{
				if ((this._ItemNumber != value))
				{
					this.OnItemNumberChanging(value);
					this.SendPropertyChanging();
					this._ItemNumber = value;
					this.SendPropertyChanged("ItemNumber");
					this.OnItemNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ManufacturerId", DbType="Int NOT NULL")]
		public int ManufacturerId
		{
			get
			{
				return this._ManufacturerId;
			}
			set
			{
				if ((this._ManufacturerId != value))
				{
					if (this._Manufacturer.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnManufacturerIdChanging(value);
					this.SendPropertyChanging();
					this._ManufacturerId = value;
					this.SendPropertyChanged("ManufacturerId");
					this.OnManufacturerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Length", DbType="Decimal(9,6)")]
		public System.Nullable<decimal> Length
		{
			get
			{
				return this._Length;
			}
			set
			{
				if ((this._Length != value))
				{
					this.OnLengthChanging(value);
					this.SendPropertyChanging();
					this._Length = value;
					this.SendPropertyChanged("Length");
					this.OnLengthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Width", DbType="Decimal(9,6)")]
		public System.Nullable<decimal> Width
		{
			get
			{
				return this._Width;
			}
			set
			{
				if ((this._Width != value))
				{
					this.OnWidthChanging(value);
					this.SendPropertyChanging();
					this._Width = value;
					this.SendPropertyChanged("Width");
					this.OnWidthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Height", DbType="Decimal(9,6)")]
		public System.Nullable<decimal> Height
		{
			get
			{
				return this._Height;
			}
			set
			{
				if ((this._Height != value))
				{
					this.OnHeightChanging(value);
					this.SendPropertyChanging();
					this._Height = value;
					this.SendPropertyChanged("Height");
					this.OnHeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weight", DbType="Decimal(9,6)")]
		public System.Nullable<decimal> Weight
		{
			get
			{
				return this._Weight;
			}
			set
			{
				if ((this._Weight != value))
				{
					this.OnWeightChanging(value);
					this.SendPropertyChanging();
					this._Weight = value;
					this.SendPropertyChanged("Weight");
					this.OnWeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsMAP", DbType="Bit NOT NULL")]
		public bool IsMAP
		{
			get
			{
				return this._IsMAP;
			}
			set
			{
				if ((this._IsMAP != value))
				{
					this.OnIsMAPChanging(value);
					this.SendPropertyChanging();
					this._IsMAP = value;
					this.SendPropertyChanged("IsMAP");
					this.OnIsMAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDiscontinued", DbType="Bit NOT NULL")]
		public bool IsDiscontinued
		{
			get
			{
				return this._IsDiscontinued;
			}
			set
			{
				if ((this._IsDiscontinued != value))
				{
					this.OnIsDiscontinuedChanging(value);
					this.SendPropertyChanging();
					this._IsDiscontinued = value;
					this.SendPropertyChanged("IsDiscontinued");
					this.OnIsDiscontinuedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes", DbType="NVarChar(1000)")]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this.OnNotesChanging(value);
					this.SendPropertyChanging();
					this._Notes = value;
					this.SendPropertyChanged("Notes");
					this.OnNotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Product_AllOrdersData", Storage="_AllOrdersDatas", ThisKey="ASIN", OtherKey="asin")]
		public EntitySet<AllOrdersData> AllOrdersDatas
		{
			get
			{
				return this._AllOrdersDatas;
			}
			set
			{
				this._AllOrdersDatas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Product_UnsuppressedInventoryData", Storage="_UnsuppressedInventoryDatas", ThisKey="ASIN", OtherKey="asin")]
		public EntitySet<UnsuppressedInventoryData> UnsuppressedInventoryDatas
		{
			get
			{
				return this._UnsuppressedInventoryDatas;
			}
			set
			{
				this._UnsuppressedInventoryDatas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Product_FeePreviewData", Storage="_FeePreviewDatas", ThisKey="ASIN", OtherKey="asin")]
		public EntitySet<FeePreviewData> FeePreviewDatas
		{
			get
			{
				return this._FeePreviewDatas;
			}
			set
			{
				this._FeePreviewDatas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Manufacturer_Product", Storage="_Manufacturer", ThisKey="ManufacturerId", OtherKey="ManufacturerId", IsForeignKey=true)]
		public Manufacturer Manufacturer
		{
			get
			{
				return this._Manufacturer.Entity;
			}
			set
			{
				Manufacturer previousValue = this._Manufacturer.Entity;
				if (((previousValue != value) 
							|| (this._Manufacturer.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Manufacturer.Entity = null;
						previousValue.Products.Remove(this);
					}
					this._Manufacturer.Entity = value;
					if ((value != null))
					{
						value.Products.Add(this);
						this._ManufacturerId = value.ManufacturerId;
					}
					else
					{
						this._ManufacturerId = default(int);
					}
					this.SendPropertyChanged("Manufacturer");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PriceHistory_Product", Storage="_PriceHistory", ThisKey="ASIN", OtherKey="ASIN", IsForeignKey=true)]
		public PriceHistory PriceHistory
		{
			get
			{
				return this._PriceHistory.Entity;
			}
			set
			{
				PriceHistory previousValue = this._PriceHistory.Entity;
				if (((previousValue != value) 
							|| (this._PriceHistory.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PriceHistory.Entity = null;
						previousValue.Products.Remove(this);
					}
					this._PriceHistory.Entity = value;
					if ((value != null))
					{
						value.Products.Add(this);
						this._ASIN = value.ASIN;
					}
					else
					{
						this._ASIN = default(string);
					}
					this.SendPropertyChanged("PriceHistory");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_AllOrdersDatas(AllOrdersData entity)
		{
			this.SendPropertyChanging();
			entity.Product = this;
		}
		
		private void detach_AllOrdersDatas(AllOrdersData entity)
		{
			this.SendPropertyChanging();
			entity.Product = null;
		}
		
		private void attach_UnsuppressedInventoryDatas(UnsuppressedInventoryData entity)
		{
			this.SendPropertyChanging();
			entity.Product = this;
		}
		
		private void detach_UnsuppressedInventoryDatas(UnsuppressedInventoryData entity)
		{
			this.SendPropertyChanging();
			entity.Product = null;
		}
		
		private void attach_FeePreviewDatas(FeePreviewData entity)
		{
			this.SendPropertyChanging();
			entity.Product = this;
		}
		
		private void detach_FeePreviewDatas(FeePreviewData entity)
		{
			this.SendPropertyChanging();
			entity.Product = null;
		}
	}
}
#pragma warning restore 1591
